-- MySQL Script generated by MySQL Workbench
-- 11/03/15 15:32:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mytwitter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mytwitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytwitter` DEFAULT CHARACTER SET utf8 ;
USE `mytwitter` ;

-- -----------------------------------------------------
-- Table `mytwitter`.`twits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytwitter`.`twits` ;

CREATE TABLE IF NOT EXISTS `mytwitter`.`twits` (
  `id` INT(11) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `mentioned_user_id` INT(11) NOT NULL,
  `content` VARCHAR(200) NULL DEFAULT NULL,
  `posted_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mytwitter`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytwitter`.`users` ;
CREATE TABLE IF NOT EXISTS `mytwitter`.`users` (
  `id` INT(11) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birthdate` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profile_picture` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `mytwitter` ;

-- -----------------------------------------------------
-- Placeholder table for view `mytwitter`.`v_twits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytwitter`.`v_twits` (
	`twit_id` INT, 
    `user_id` INT, 
    `content` INT, 
    `posted_date` INT, 
    `full_name` INT, 
    `nickname` INT,
    `email` INT);

-- -----------------------------------------------------
-- Table `mytwitter`.`hashtags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytwitter`.`hashtags` ;
CREATE TABLE IF NOT EXISTS `mytwitter`.`hashtags` (
  `id` INT(11) NOT NULL,
  `count` INT(11) NOT NULL,
  `content` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE (content))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `mytwitter`.`twit_hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytwitter`.`twit_hashtags` ;
CREATE TABLE IF NOT EXISTS `mytwitter`.`twit_hashtags` (
  `hashtag_id` INT(11) NOT NULL,
  `twit_id` INT(11) NOT NULL,
  PRIMARY KEY (hashtag_id, twit_id),
  FOREIGN KEY (`hashtag_id`) REFERENCES hashtags(id)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`twit_id`) REFERENCES twits(id)
	ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `mytwitter`.`twit_hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytwitter`.`user_twits` ;
CREATE TABLE IF NOT EXISTS `mytwitter`.`user_twits` (
  `id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `twit_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- View `mytwitter`.`v_twits`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mytwitter`.`v_twits` ;
DROP TABLE IF EXISTS `mytwitter`.`v_twits`;
USE `mytwitter`;
CREATE  OR REPLACE 
ALGORITHM=UNDEFINED 
DEFINER=`root`@`localhost` 
SQL SECURITY DEFINER VIEW `mytwitter`.`v_twits` AS 
select `mytwitter`.`twits`.`id` AS `twit_id`,
	`mytwitter`.`twits`.`user_id` AS `user_id`,
	`mytwitter`.`twits`.`content` AS `content`,
	`mytwitter`.`twits`.`posted_date` AS `posted_date`,
    `mytwitter`.`twits`.`mentioned_user_id` AS `mentioned_user_id`,
	`mytwitter`.`users`.`full_name` AS `full_name`,
	`mytwitter`.`users`.`nickname` AS `nickname`,
	`mytwitter`.`users`.`email` AS `email` 
from (`mytwitter`.`twits`
	join `mytwitter`.`users` on(
		(`mytwitter`.`twits`.`user_id` = `mytwitter`.`users`.`id`)
	)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;